management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
  endpoint:
    health:
      show-details: ALWAYS

spring:
  task:
    pool:
      maxPoolSize: 100
  security:
    basic:
      enabled: true
    user:
      name: user
      password: 234