eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: user
      password: 234
server:
  port: 8761