eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://user:234@localhost:8761/eureka/
    healthcheck:
      enabled: true

feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: true
  okhttp:
    enabled: true

spring:
  application:
    name: feign
server:
  port: 8083
